name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Checkout submodules using a PAT
        run: |
          git config --file .gitmodules --get-regexp url | while read url; do
            git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.CI_PAT }}:${{ secrets.CI_PAT }}@github.com\//")
          done
          git submodule sync
          git submodule update --init --recursive

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Make Directory for deliver
        run: mkdir deploy

      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy/

      - name: Copy appspec
        run: cp ./appspec.yml ./deploy/

      - name: Copy shell
        run: cp ./deploy.sh ./deploy/

      - name: Make zip file
        run: zip -r ./gold-dduck-jar.zip ./deploy

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to AWS S3
        run: |
          aws s3 cp \
          --region ap-northeast-2 \
          --acl private \
          ./gold-dduck-jar.zip s3://gold-dduck/

      - name: Code Deploy
        run: |
          aws deploy create-deployment \
          --application-name github-actions-deploy \
          --deployment-group-name github-actions-group \
          --file-exists-behavior OVERWRITE \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --s3-location bucket=gold-dduck,bundleType=zip,key=gold-dduck-jar.zip \
          --region ap-northeast-2
